version: '3.9'

networks:
  wordpress:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - wordpress
  
  #Database service for wordpress and here we use mysql 
  mysql:
    image: mysql:5.7.40
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - wordpress
    volumes:
      - ./mysql:/var/lib/mysql
  
  #PHP service section for handling wordpress
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./wordpress:/var/www/html:delegated
    networks:
      - wordpress


  #Section deails with wordpress configuration
  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: wp
    entrypoint: ['wp', '--allow-root']
    volumes:
      - ./wordpress:/var/www/html:delegated
    networks:
      - wordpress